[build]
  command = "python -m pip install --upgrade pip && pip install -r requirements.txt && npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.8.12"
  NEXT_TELEMETRY_DISABLED = "1"
  PIP_VERSION = "23.3.1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"