[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next/standalone"

[build.environment]
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.8.12"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs" 