[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_WEBPACK_USEPOLLING = "1"
  NEXT_SHARP_PATH = "/tmp/node_modules/sharp"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    skipBuildCache = true
    experimentalBundling = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"